services:
  ros_bridge_s:
    image: ros_bridge_i
    container_name: ros_bridge_c
    build:
      # set the build context to the directory containing build files
      context: .
      dockerfile: Dockerfile
    environment:
    - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
    - ROS_LOCALHOST_ONLY=0
    - ROS_DOMAIN_ID=16
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - CYCLONEDDS_URI=/ros2_ws/.zbashrc_cyclonedds.xml
    # give the container access to the host's network
    volumes:
      - /dev/shm:/dev/shm
    network_mode: host
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    # run the entrypoint script
    entrypoint: /entrypoint.sh
