version: "3"

services:
  ros_bridge_s:
    image: ros_noetic_i
    container_name: ros_noetic_c
    build:
      # set the build context to the directory containing build files
      context: ..
      dockerfile: ros1_docker/Dockerfile
    environment:
    - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
    # give the container access to the host's network
    network_mode: host
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    # run the entrypoint script
    # entrypoint: /entrypoint.sh
