version: "3"

services:
  ros_bridge:
    image: ros_bridge_i
    container_name: ros_bridge_c
    build:
      # set the build context to the directory containing build files
      context: .
      dockerfile: Dockerfile
    network_mode: host
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    # run the entrypoint script
    entrypoint: /entrypoint.sh
    # environment:
    #   - ROS_DOMAIN_ID=23